version: '3'
services:
  app:
    container_name: watanabe-frontend-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./:/app/
      - node_modules:/app/node_modules
    entrypoint: ["npm", "run", "dev"]

volumes:
  node_modules: